services:
  - type: web
    name: wantu
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    plan: free
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: NODE_OPTIONS
        value: "--openssl-legacy-provider"
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_BUCKET
        sync: false

  - type: worker
    name: wantu-sidekiq
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec sidekiq -C config/sidekiq.yml"
    plan: free
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY_BASE
        generateValue: true